name: port_fol
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations: ^2.0.11
  url_launcher: ^6.2.6
  lottie: ^3.1.2
  rive_animated_icon: ^1.1.2
  fluttertoast: ^8.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

dependency_overrides:
  leak_tracker: ^10.0.5
  leak_tracker_flutter_testing: ^3.0.5
  leak_tracker_testing: ^3.0.1
  material_color_utilities: ^0.11.1
  url_launcher_android: ^6.3.3
  meta: ^1.15.0
  test_api: ^0.7.1
  vm_service: ^14.2.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
